name: Frontend CD

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
    permissions:
      contents: read
      security-events: write

  deploy:
    name: Build and deploy frontend to server
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail
            # check if directory exists, if not create it
            if [ ! -d "/home/ubuntu/pulsepoint-frontend-prod" ]; then
              echo "Directory /home/ubuntu/pulsepoint-frontend-prod does not exist. Creating it..."
              mkdir -p /home/ubuntu/pulsepoint-frontend-prod
            fi

            cd /home/ubuntu/pulsepoint-frontend-prod
            if [ -d "/home/ubuntu/pulsepoint-frontend-prod/.git" ]; then
              echo "Repo already cloned, pulling latest..."
              git switch main
              git pull origin main
            else
              echo "No repo found. Clearing directory and cloning fresh..."
              find /home/ubuntu/pulsepoint-frontend-prod -mindepth 1 -delete
              git clone https://github.com/404-Fixers/Pulse_Point_FE.git .
            fi
            npm ci --omit=dev
            npm run build
            pm2 restart pulsepoint-frontend-prod || pm2 start npm --name "pulsepoint-frontend-prod" -- start

      - name: Reload web server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl reload nginx